addr = "0.0.0.0:8443"

[tls]
cert_path = "certs/cert.pem"
private_key_path = "certs/key.pem"

[upstream]
addr = "127.0.0.1:8080"
pool_size = 10
keep_alive_secs = 60
timeout_secs = 2
health_check_interval_secs = 5
health_check_timeout_secs = 1
health_check_path = "/get"

[telemetry]
otlp_endpoint = "http://localhost:4317"

[metrics]
addr = "0.0.0.0:9090"
